//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [Serializable]
    [XmlRoot("Personas")]
    public partial class Persona
    {
        public Persona()
        {
            this.Rol = new HashSet<Rol>();
        }
        [XmlElement("id")]

        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string genero { get; set; }
        public string lugar_nacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string estado_civil { get; set; }
        public string ocupacion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public int id_rol { get; set; }

        public virtual ICollection<Rol> Rol { get; set; }

    }
}
